spring:
  application:
    name: api
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o-mini
  datasource:
    hikari:
      pool-name: mysql-main-pool
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true

storage:
  local:
    root-dir: ./uploads
    base-url: http://localhost:8080/files

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        name: JSESSIONID
      timeout: 30m

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    enable:
      hibernate: true
    tags:
      application: ${spring.application.name}
