spring:
  application:
    name: api
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-4o-mini
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

sentry:
  enabled: false # 로컬에선 Sentry를 끕니다.

  autoconfigure:
    exclude:
      - io.awspring.cloud.autoconfigure.s3.S3AutoConfiguration

cloud:
  aws:
    s3:
      endpoint: ${SUPABASE_S3_ENDPOINT}
      path-style-access-enabled: true
    region:
      static: ${SUPABASE_S3_REGION:ap-southeast-1}
      auto: false
    credentials:
      access-key: ${SUPABASE_S3_ACCESS_KEY}
      secret-key: ${SUPABASE_S3_SECRET_KEY}
    stack:
      auto: false

storage:
  s3:
    bucket: ${SUPABASE_S3_BUCKET}
    endpoint: ${SUPABASE_S3_ENDPOINT}
  local:
    root-dir: ./uploads
    base-url: http://pcserver.cloud/files

server:
  servlet:
    session:
      cookie:
        http-only: true
        same-site: lax
        name: JSESSIONID
      timeout: 30m
