spring:
  application:
    name: api
  datasource:
    hikari:
      pool-name: mysql-main-pool
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000

oauth2:
  redirect-uri: ${OAUTH2_REDIRECT_URI:https://capstone-frontend.jinhy.uk/oauth2/callback}

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    prometheus:
      enabled: true
    health:
      show-details: always
  metrics:
    enable:
      hibernate: true
    tags:
      application: ${spring.application.name}
